# Project - Data Cleaning

## Introduction
In this lab, we'll make use of everything we've learned about pandas, data cleaning, and Exploratory Data Analysis. In order to complete this lab, you'll have to make import, clean, combine, reshape, and visualize data to answer questions provided, as well as your own questions!

## Objectives
You will be able to:
* Show mastery of the content covered in this section

## The Dataset
In this lab, we'll work with the comprehensive [Super Heroes Dataset](https://www.kaggle.com/claudiodavi/superhero-set/data), which can be found on Kaggle!

## Goals
* Use all available pandas knowledge to clean the dataset and deal with null values
* Use Queries and aggregations to group the data into interesting subsets as needed
* Use descriptive statistics and data visualization to find answers to questions we may have about the data. 

## Getting Started

In the cell below:

* Import and alias pandas as `pd`
* Import and alias numpy as `np`
* Import and alias seaborn as `sns`
* Import and alias matplotlib.pyplot as `plt`
* Set matplotlib visualizations to display inline in the notebook

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

For this lab, our dataset is split among two different sources--`heroes_information.csv` and `super_hero_powers.csv`.

Use pandas to read in each file and store them in DataFrames in the appropriate variables below. Then, display the head of each to ensure that everything loaded correctly.

In [2]:
heroes_df = pd.read_csv('heroes_information.csv')
powers_df = pd.read_csv('super_hero_powers.csv')

heroes_df.head()

,Unnamed: 0,name,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
0,0,A-Bomb,Male,yellow,Human,No Hair,203.0,Marvel Comics,-,good,441.0
1,1,Abe Sapien,Male,blue,Icthyo Sapien,No Hair,191.0,Dark Horse Comics,blue,good,65.0
2,2,Abin Sur,Male,blue,Ungaran,No Hair,185.0,DC Comics,red,good,90.0
3,3,Abomination,Male,green,Human / Radiation,No Hair,203.0,Marvel Comics,-,bad,441.0
4,4,Abraxas,Male,blue,Cosmic Entity,Black,-99.0,Marvel Comics,-,bad,-99.0

In [3]:
powers_df.head()

,hero_names,Agility,Accelerated Healing,Lantern Power Ring,Dimensional Awareness,Cold Resistance,Durability,Stealth,Energy Absorption,Flight,...,Web Creation,Reality Warping,Odin Force,Symbiote Costume,Speed Force,Phoenix Force,Molecular Dissipation,Vision - Cryo,Omnipresent,Omniscient
0,3-D Man,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,A-Bomb,False,True,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,Abe Sapien,True,True,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,Abin Sur,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,Abomination,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

It looks as if the heroes information dataset contained an index column.  We did not specify that this dataset contained an index column, because we hadn't seen it yet. Pandas does not know how to tell apart an index column from any other data, so it stored it with the column name `Unnamed: 0`.  

Our DataFrame provided row indices by default, so this column is not needed.  Drop it from the DataFrame in place in the cell below, and then display the head of `heroes_df` to ensure that it worked properly.

In [4]:
heroes_df.drop('Unnamed: 0', axis = 1, inplace = True)

In [5]:
heroes_df.isna().sum()

name           0
Gender         0
Eye color      0
Race           0
Hair color     0
Height         0
Publisher     15
Skin color     0
Alignment      0
Weight         2
dtype: int64

## Familiarize Yourself With the Dataset

The first step in our Exploratory Data Analysis will be to get familiar with the data.  This step includes:

* Understanding the dimensionality of your dataset
* Investigating what type of data it contains, and the data types used to store it
* Discovering how missing values are encoded, and how many there are
* Getting a feel for what information it does and doesn't contain

In the cell below, get the descriptive statistics of each DataFrame.

In [6]:
heroes_df.describe()

           Height      Weight
count  734.000000  732.000000
mean   102.254087   43.855191
std    139.624543  130.823733
min    -99.000000  -99.000000
25%    -99.000000  -99.000000
50%    175.000000   62.000000
75%    185.000000   90.000000
max    975.000000  900.000000

## Dealing with Null Values

Starting in the cell below, detect and deal with any null values in either data frame.  Then, explain your methodology for detecting and dealing with outliers in the markdown section below.  Be sure to explain your strategy for dealing with null values in numeric columns, as well as your strategy for dealing with null values in non-numeric columns.  

Note that if you need to add more cells to write code in, you can do this by:

**1.** Highlighting a cell and then pressing `ESC` to enter command mode.  
**2.** Press `A` to add a cell above the highlighted cell, or `B` to add a cell below the highlighted cell. 

Describe your strategy below this line:
____________________________________________________________________________________________________________________________

In [7]:
heroes_df.isna().sum()

name           0
Gender         0
Eye color      0
Race           0
Hair color     0
Height         0
Publisher     15
Skin color     0
Alignment      0
Weight         2
dtype: int64

In [8]:
heroes_df.dropna(inplace = True)

In [9]:
heroes_df['Publisher'].isna().sum()

0

In [10]:
heroes_df[heroes_df['name'].duplicated(keep = False)]

,name,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
22,Angel,Male,blue,-,Blond,183.0,Marvel Comics,-,good,68.0
23,Angel,Male,-,Vampire,-,-99.0,Dark Horse Comics,-,good,-99.0
47,Atlas,Male,brown,Mutant,Red,183.0,Marvel Comics,-,good,101.0
48,Atlas,Male,blue,God / Eternal,Brown,198.0,DC Comics,-,bad,126.0
49,Atom,Male,blue,-,Red,178.0,DC Comics,-,good,68.0
50,Atom,Male,-,-,-,-99.0,DC Comics,-,good,-99.0
62,Batgirl,Female,-,-,-,-99.0,DC Comics,-,good,-99.0
63,Batgirl,Female,green,Human,Red,170.0,DC Comics,-,good,57.0
68,Batman,Male,blue,Human,black,188.0,DC Comics,-,good,95.0
69,Batman,Male,blue,Human,Black,178.0,DC Comics,-,good,77.0
96,Black Canary,Female,blue,Human,Blond,165.0,DC Comics,-,good,58.0
97,Black Canary,Female,blue,Metahuman,Blond,170.0,DC Comics,-,good,59.0
115,Blizzard,Male,-,-,-,-99.0,Marvel Comics,-,bad,-99.0
116,Blizzard,Male,-,-,Brown,-99.0,Marvel Comics,-,bad,-99.0
122,Blue Beetle,Male,blue,-,Brown,-99.0,DC Comics,-,good,-99.0
123,Blue Beetle,Male,-,-,-,-99.0,DC Comics,-,good,-99.0
155,Captain Marvel,Female,blue,Human-Kree,Blond,180.0,Marvel Comics,-,good,74.0
156,Captain Marvel,Male,blue,Human,Black,193.0,DC Comics,-,good,101.0
259,Firestorm,Male,brown,-,Black,-99.0,DC Comics,-,good,-99.0
260,Firestorm,Male,blue,Human,Auburn,188.0,DC Comics,-,good,91.0
289,Goliath,Male,-,-,-,-99.0,Marvel Comics,-,good,-99.0
290,Goliath,Male,-,Human,-,-99.0,Marvel Comics,-,good,-99.0
291,Goliath,Male,-,Human,-,-99.0,Marvel Comics,-,good,-99.0
481,Namor,Male,-,-,-,-99.0,Marvel Comics,-,good,-99.0
482,Namor,Male,grey,Atlantean,Black,188.0,Marvel Comics,-,good,125.0
496,Nova,Male,brown,Human,Brown,185.0,Marvel Comics,-,good,86.0
497,Nova,Female,white,Human / Cosmic,Red,163.0,Marvel Comics,gold,good,59.0
617,Speedy,Male,-,Human,-,-99.0,DC Comics,-,good,-99.0
618,Speedy,Female,green,Human,Brown,-99.0,DC Comics,-,good,-99.0
622,Spider-Man,Male,hazel,Human,Brown,178.0,Marvel Comics,-,good,74.0
623,Spider-Man,-,red,Human,Brown,178.0,Marvel Comics,-,good,77.0
624,Spider-Man,Male,brown,Human,Black,157.0,Marvel Comics,-,good,56.0
673,Toxin,Male,blue,Symbiote,Brown,188.0,Marvel Comics,-,good,97.0
674,Toxin,Male,black,Symbiote,Blond,191.0,Marvel Comics,-,good,117.0
695,Vindicator,Female,green,Human,Red,165.0,Marvel Comics,-,good,54.0
696,Vindicator,Male,-,-,-,-99.0,Marvel Comics,-,good,-99.0

In [11]:
heroes_df[heroes_df.duplicated(keep = False)]

,name,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
290,Goliath,Male,-,Human,-,-99.0,Marvel Comics,-,good,-99.0
291,Goliath,Male,-,Human,-,-99.0,Marvel Comics,-,good,-99.0

In [12]:
heroes_df = heroes_df[~heroes_df['name'].duplicated(keep = 'first')]

In [13]:
heroes_df['Weight'] = heroes_df['Weight'].apply(lambda x: np.mean(heroes_df['Weight']) if x == -99 else x)

In [14]:
heroes_df['Height'].replace(-99, np.median(heroes_df['Height']), inplace= True)

In [15]:
heroes_df['Weight'].value_counts().head()

47.22    217
54.00     23
79.00     23
81.00     22
90.00     19
Name: Weight, dtype: int64

## Joining, Grouping, and Aggregating

In the cell below, join the two DataFrames.  Think about which sort of join you should use, as well as which columns you should join on.  Rename columns and manipulate as needed.  

**_HINT:_** If the join throws an error message, consider setting the column you want to join on as the index for each DataFrame.

In [17]:
powers_df.rename(columns={'hero_names':'name'}, inplace=True)

In [18]:
combined_df = pd.merge(heroes_df, powers_df, how = 'inner', left_index = True, right_index = True)

In [11]:
pd.merge(heroes_df, powers_df, how='inner', on=heroes_df['name'])

KeyError: 0                 A-Bomb
1             Abe Sapien
2               Abin Sur
3            Abomination
4                Abraxas
5          Absorbing Man
6            Adam Monroe
7           Adam Strange
8               Agent 13
9              Agent Bob
10            Agent Zero
11            Air-Walker
12                  Ajax
13            Alan Scott
14           Alex Mercer
15          Alex Woolsly
16     Alfred Pennyworth
17                 Alien
18      Allan Quatermain
19                 Amazo
20                  Ammo
21        Ando Masahashi
22                 Angel
23                 Angel
24            Angel Dust
25       Angel Salvadore
26                Angela
27            Animal Man
28             Annihilus
29               Ant-Man
             ...
704               Walrus
705          War Machine
706              Warbird
707              Warlock
708                 Warp
709              Warpath
710                 Wasp
711              Watcher
712            Weapon XI
713         White Canary
714          White Queen
715             Wildfire
716       Winter Soldier
717              Wiz Kid
718            Wolfsbane
719            Wolverine
720          Wonder Girl
721           Wonder Man
722         Wonder Woman
723               Wondra
724       Wyatt Wingfoot
725                 X-23
726                X-Man
727          Yellow Claw
728         Yellowjacket
729      Yellowjacket II
730                 Ymir
731                 Yoda
732              Zatanna
733                 Zoom
Name: name, Length: 719, dtype: object

In the cell below, subset male and female heroes into different dataframes.  Create a scatterplot of the height and weight of each hero, with weight as the y-axis.  Plot both the male and female heroes subset into each dataframe, and make the color for each point in the scatterplot correspond to the gender of the superhero.

## Some Initial Investigation

Next, slice the DataFrame as needed and visualize the distribution of heights and weights by gender.  You should have 4 total plots.  

In the cell below:

* Slice the DataFrame into separate DataFrames by gender
* Complete the `show_distplot` function.  This helper function should take in a DataFrame, a string containing the gender we want to visualize, and and the column name we want to visualize by gender. The function should display a distplot visualization from seaborn of the column/gender combination.  

Hint: Don't forget to check the [seaborn documentation for distplot](https://seaborn.pydata.org/generated/seaborn.distplot.html) if you have questions about how to use it correctly!

In [ ]:
male_heroes_df = None
female_heroes_df = None

def show_distplot(dataframe, gender, column_name):
    pass

In [ ]:
# Male Height

In [ ]:
# Male Weight

In [ ]:
# Female Height

In [ ]:
# Female Weight

Discuss your findings from the plots above, with respect to the distribution of height and weight by gender.  Your explanation should include discussion of any relevant summary statistics, including mean, median, mode, and the overall shape of each distribution.  

Wite your answer below this line:
____________________________________________________________________________________________________________________________

### Sample Question: Most Common Powers

The rest of this notebook will be left to you to investigate the dataset by formulating your own questions, and then seeking answers using pandas and numpy.  Every answer should include some sort of visualization, when appropriate. Before moving on to formulating your own questions, use the dataset to answer the following questions about superhero powers:

* What are the 5 most common powers overall?
* What are the 5 most common powers in the Marvel Universe?
* What are the 5 most common powers in the DC Universe?

Analyze the results you found above to answer the following question:

How do the top 5 powers in the Marvel and DC universes compare?  Are they similar, or are there significant differences? How do they compare to the overall trends in the entire Superheroes dataset?

Wite your answer below this line:
____________________________________________________________________________________________________________________________


### Your Own Investigation

For the remainder of this lab, you'll be focusing on coming up with and answering your own question, just like we did above.  Your question should not be overly simple, and should require both descriptive statistics and data visualization to answer.  In case you're unsure of what questions to ask, some sample questions have been provided below.

Pick one of the following questions to investigate and answer, or come up with one of your own!

* Which powers have the highest chance of co-occurring in a hero (e.g. super strength and flight), and does this differ by gender?
* Is there a relationship between a hero's height and weight and their powerset?
* What is the distribution of skin colors amongst alien heroes?

Explain your question below this line:
____________________________________________________________________________________________________________________________



Some sample cells have been provided to give you room to work. If you need to create more cells, you can do this easily by:

1. Highlighting a cell and then pressing `esc` to enter command mode.
1. Pressing `b` to add a cell below the currently highlighted cell, or `a` to add one above it.  

Be sure to include thoughtful, well-labeled visualizations to back up your analysis!

## Summary

In this lab, we demonstrated our mastery of:
* Using all of our Pandas knowledge to date to clean the dataset and deal with null values
* Using Queries and aggregations to group the data into interesting subsets as needed
* Using descriptive statistics and data visualization to find answers to questions we may have about the data